### ISSUE TITLE
pip install -r kubespray/requirements.txt fails in the container

### ISSUE THREAD

**Issue by arashkaffamanesh** [kubernauts/tk8#26]
`pip install -r kubespray/requirements.txt`

fails in the tk8 container image:

```
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3xxUgv/bcrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-Z8WEoI/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-3xxUgv/bcrypt/
```
which leads to:

```
/tk8 # tk8 cluster aws -i
Found Ansible at /usr/bin/ansible
ansible 2.5.5
  config file = /tk8/ansible.cfg
  configured module search path = ['/tk8/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.4 (default, May  1 2018, 11:38:09) [GCC 6.4.0]
Configuration folder already exists
coreos
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/tk8/kubespray/roles/vault/handlers/main.yml': line 44, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: unseal vault
  ^ here
```

**Comment by arashkaffamanesh** [comment]
workaround for now:

`vi /tk8/kubespray/roles/vault/handlers/main.yml`

and remove:

```
- name: unseal vault
  hashivault_unseal:
    url: "{{ vault_leader_url | default('https://localhost:8200') }}"
    token: "{{ vault_root_token }}"
    ca_cert: "{{ vault_cert_dir }}/ca.pem"
    keys: "{{ item }}"
  with_items: "{{ vault_unseal_keys|default([]) }}"
```
